Added -fPIC to compiler flags, as travis is complaining about that
/usr/bin/g++-4.9    -std=c++1y -g -I/home/travis/build/Grumbel/evtest-qt/build-Debug -I/home/travis/build/Grumbel/evtest-qt -isystem /usr/include/qt5/QtWidgets -isystem /usr/include/qt5/QtGui -isystem /usr/include/qt5/QtCore -isystem /usr/include/qt5 -isystem /usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64    -pedantic -Wall -Wextra -Wno-c++0x-compat -Wnon-virtual-dtor -Weffc++ -Wconversion -Wshadow -Wcast-qual -Winit-self -Wno-unused-parameter -Werror -o CMakeFiles/jslib.dir/src/axis_widget.cpp.o -c /home/travis/build/Grumbel/evtest-qt/src/axis_widget.cpp
In file included from /usr/include/qt5/QtGui/qwindowdefs.h:45:0,
                 from /usr/include/qt5/QtWidgets/qwidget.h:45,
                 from /usr/include/qt5/QtWidgets/QWidget:1,
                 from /home/travis/build/Grumbel/evtest-qt/src/axis_widget.hpp:20,
                 from /home/travis/build/Grumbel/evtest-qt/src/axis_widget.cpp:17:
/usr/include/qt5/QtCore/qglobal.h:1079:4: error: #error "You must build your code with position independent code if Qt was built with -reduce-relocations. " "Compile your code with -fPIC or -fPIE."
 #  error "You must build your code with position independent code if Qt was built with -reduce-relocations. "\
    ^