Removed non-copy from EvdevState due to travis complaining
/usr/bin/g++-4.9    -std=c++1y -g -I/home/travis/build/Grumbel/evtest-qt/build-Debug -I/home/travis/build/Grumbel/evtest-qt -isystem /usr/include/qt5/QtWidgets -isystem /usr/include/qt5/QtGui -isystem /usr/include/qt5/QtCore -isystem /usr/include/qt5 -isystem /usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64    -fPIC -pedantic -Wall -Wextra -Wno-c++0x-compat -Wnon-virtual-dtor -Weffc++ -Wconversion -Wshadow -Wcast-qual -Winit-self -Wno-unused-parameter -Werror -o CMakeFiles/jslib.dir/src/multitouch_widget.cpp.o -c /home/travis/build/Grumbel/evtest-qt/src/multitouch_widget.cpp
In file included from /home/travis/build/Grumbel/evtest-qt/src/evdev_widget.hpp:42:0,
                 from /home/travis/build/Grumbel/evtest-qt/src/evdev_widget.cpp:17:
/usr/include/qt5/QtCore/qobjectdefs_impl.h: In instantiation of ‘struct QtPrivate::AreArgumentsCompatible<EvdevState, EvdevState>’:
/usr/include/qt5/QtCore/qobjectdefs_impl.h:595:21:   required from ‘struct QtPrivate::CheckCompatibleArguments<QtPrivate::List<const EvdevState&>, QtPrivate::List<const EvdevState&> >’
/usr/include/qt5/QtCore/qobject.h:239:80:   required from ‘static QMetaObject::Connection QObject::connect(const typename QtPrivate::FunctionPointer<Func>::Object*, Func1, const typename QtPrivate::FunctionPointer<Func2>::Object*, Func2, Qt::ConnectionType) [with Func1 = void (EvdevState::*)(const EvdevState&) const; Func2 = void (MultitouchWidget::*)(const EvdevState&); typename QtPrivate::FunctionPointer<Func>::Object = EvdevState; typename QtPrivate::FunctionPointer<Func2>::Object = MultitouchWidget]’
/home/travis/build/Grumbel/evtest-qt/src/evdev_widget.cpp:63:75:   required from here
/home/travis/build/Grumbel/evtest-qt/src/evdev_state.hpp:79:3: error: ‘EvdevState::EvdevState(const EvdevState&)’ is private
   EvdevState(const EvdevState&) = delete;
   ^
In file included from /usr/include/qt5/QtCore/qobjectdefs.h:47:0,
                 from /usr/include/qt5/QtCore/qobject.h:47,
                 from /usr/include/qt5/QtCore/qcoreapplication.h:45,
                 from /usr/include/qt5/QtWidgets/qapplication.h:45,
                 from /usr/include/qt5/QtWidgets/QApplication:1,
                 from /home/travis/build/Grumbel/evtest-qt/src/evdev_widget.hpp:20,
                 from /home/travis/build/Grumbel/evtest-qt/src/evdev_widget.cpp:17:
/usr/include/qt5/QtCore/qobjectdefs_impl.h:569:43: error: within this context
         enum { value = sizeof(test(dummy())) == sizeof(int) };
                                           ^